#!/usr/bin/env bash

# Based on https://mths.be/macos and
# https://github.com/pawelgrzybek/dotfiles/blob/master/setup-macos.sh
# For a guide on how to obtain these yourself, see:
# https://pawelgrzybek.com/change-macos-user-preferences-via-command-line/

# Close any open System Preferences panes, to prevent them from overriding
# settings we're about to change
osascript -e 'tell application "System Preferences" to quit'

#----------------------------------------------------------------------------
# Dock

# System Preferences > Dock > [X] Automatically hide and show the Dock
defaults write com.apple.dock autohide -bool true

# System Preferences > Dock > [X] Magnification
defaults write com.apple.dock magnification -bool true

# System Preferences > Dock > Magnification Size
defaults write com.apple.dock largesize -int 95

killall Dock
#----------------------------------------------------------------------------
# Trackpad
#
# It seems that the standard 'write' sets the behaviour,
# but it is also required to do a -currentHost -g 'write' so that
# the System Preferences UI is in sync.
# It also seems that a logout is necessary for changes to take effect.
# (See https://apple.stackexchange.com/a/348831)

# Zeigen und Klicken -> [ ] Nachschlagen & Datenerkennung
defaults write com.apple.AppleMultitouchTrackpad TrackpadThreeFingerTapGesture -int 0
defaults -currentHost write -g com.apple.trackpad.threeFingerTapGesture -int 0

# Zeigen und Klicken -> [X] Sekundärklick - Mit zwei Fingern klicken oder tippen
# Note: System Preferences UI doesn't seem to update.
# defaults write com.apple.AppleMultitouchTrackpad TrackpadRightClick -bool true
# defaults write com.apple.driver.AppleBluetoothMultitouch.trackpad TrackpadRightClick -bool true
# defaults -currentHost write -g com.apple.trackpad.enableSecondaryClick -bool true

#----------------------------------------------------------------------------

# Accessibility

# Display -> Cursor -> [ ] Shake mouse pointer to locate
# (logout required)
defaults write NSGlobalDomain CGDisableCursorLocationMagnification -bool YES

#----------------------------------------------------------------------------

# Frequency of software update check, in days
defaults write com.apple.SoftwareUpdate ScheduleFrequency -int 14

# Download newly available updates in background
defaults write com.apple.SoftwareUpdate AutomaticDownload -int 1

#----------------------------------------------------------------------------
# Hammerspoon

# Preferences -> [ ] Show dock icon
defaults write org.hammerspoon.Hammerspoon MJShowDockIconKey -bool false
